title = "draugelis.dev"
baseURL = "https://draugelis.dev/"
languageCode = "en"
defaultContentLanguage = "en"
theme = ["nojs", "hugo-notice"]
timeZone = "Europe/Vilnius"
canonifyURLs = true
enableRobotsTXT = true

[pagination]
pagerSize = 20

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github-dark"
    tabWidth = 4
    noClasses = false
    guessSyntax = true

[params]
  keywords = "blog,personal,devops,developer"
  dateFormat = "2006-01-02"
  customCSS = ["css/custom.css"]
  favicon = "favicon.ico"

[params.goatCounter]
  code = "draugelis"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 2
